### ISSUE TITLE
Integrate h5 and some sort of version tracking on datasets

### ISSUE THREAD

**Issue by evanberkowitz** [evanberkowitz/two-dimensional-gasses#14]
It'd be great to provide a base class that had eg. `.to_h5( ... )` and `.from_h5( ... )`, where `...` might be `h5file, path` or perhaps just `h5group` or something?

For each object property/attribute, if it's
 - [x] torch.tensor store it as a native h5 dataset
 - [x] derived from the base class use .to_h5 on it
 - [x] pickle it and store it as binary in the h5

Perhaps if a property/attribute is `_private` it should stored in a subgroup for user-friendliness?

Moreover, the base class should be able to track the version / git commit of tdg that created it.  So it will be possible to understand if there's some incompatible thing that could cause trouble or to see if the data should be tossed because there was a correctness-affecting bug in its generation.
